Repository StackStorm/st2docs, pull requests merged in 2019-05, with the labels that each got.

#897 Typo fix
  docs/source/_includes/runner_parameters/local_shell_cmd.rst
  docs/source/_includes/runner_parameters/local_shell_script.rst
  docs/source/_includes/runner_parameters/remote_shell_cmd.rst
  docs/source/_includes/runner_parameters/remote_shell_script.rst
  docs/source/known_security_issues.rst
  docs/source/reference/runners.rst
Labels: typo

#899 Use 'stable' PackageCloud repo in HA setup doc
  docs/source/reference/ha.rst
Labels: RFR, bug

#900 Fix HA docs build failure caused by updated nginx config in st2 repo
  docs/source/reference/ha.rst
Labels: bug

#907 Add ingress to the k8s/ha documentation
  docs/source/install/k8s_ha.rst
Labels: RFR, enhancement
