Repository StackStorm/st2docs, pull requests merged in 2019-10, with the labels that each got.

#933 Documenting immutable_parameters for Action Aliases.
  docs/source/chatops/aliases.rst
Labels: feature

#937 Synchronize K8s HA docs
  docs/source/install/k8s_ha.rst
Labels: enhancement

#938 Synchronize K8s HA docs (v3.1)
  docs/source/install/k8s_ha.rst
Labels: enhancement

#939 fix link to source code
  docs/source/chatops/aliases.rst
Labels: bug
