Repository StackStorm/st2docs, pull requests merged in 2020-02, with the labels that each got.

#886 Add a note on using "secret: true" for action parameter default values which use decrypt_kv Jinja filter
  docs/source/datastore.rst
Labels: security

#960 document number of workers per service
  docs/source/install/config/config.rst
  docs/source/reference/ha.rst
Labels: enhancement

#954 New example for an Orquesta workflow querying multiple parameters
  docs/source/inquiries.rst
Labels: enhancement

#962 Remove --no-site-packages flag
  Makefile
  docs/source/reference/monitoring.rst
Labels: bug

#963 Docs/correct syntax to register single packs
  docs/source/packs.rst
Labels: bug

#964 remove extra comma from json
  docs/source/_includes/_graphite_dashboard.json
  docs/source/_includes/_graphite_dashboard.rst
  docs/source/reference/metrics.rst
Labels: bug
