Repository StackStorm/st2docs, pull requests merged in 2020-12, with the labels that each got.

#1039 Updating rbac documentation
  docs/source/rbac.rst
Labels: enhancement

#1041 Remove obsolete submit debug info tool
  docs/source/troubleshooting/ask_for_support.rst
  docs/source/troubleshooting/index.rst
  docs/source/troubleshooting/submit_debug_info.rst
Labels: bug

#1043 Refactor docs building
  .circleci/config.yml
  .dockerignore
  Dockerfile
  Makefile
  docs/source/_includes/runner_parameters/action_chain.rst
  docs/source/_includes/runner_parameters/announcement.rst
  docs/source/_includes/runner_parameters/http_request.rst
  docs/source/_includes/runner_parameters/inquirer.rst
  docs/source/_includes/runner_parameters/local_shell_cmd.rst
  docs/source/_includes/runner_parameters/local_shell_script.rst
  docs/source/_includes/runner_parameters/orquesta.rst
  docs/source/_includes/runner_parameters/python_script.rst
  docs/source/_includes/runner_parameters/quick_reference.rst
  docs/source/_includes/runner_parameters/remote_shell_cmd.rst
  docs/source/_includes/runner_parameters/remote_shell_script.rst
  docs/source/_includes/runner_parameters/winrm_cmd.rst
  docs/source/_includes/runner_parameters/winrm_ps_cmd.rst
  docs/source/_includes/runner_parameters/winrm_ps_script.rst
  docs/source/_themes/sphinx_rtd_theme/static/css/theme.css
  docs/source/_themes/sphinx_rtd_theme/static/css/theme.min.css
  docs/source/reference/runners.rst
  scripts/generate-runner-parameters-documentation.py
Labels: enhancement, refactoring
