Repository StackStorm/st2docs, pull requests merged in 2020-04, with the labels that each got.

#949 Update note on supported MongoDB versions
  docs/source/install/__mongodb_note.rst
Labels: enhancement

#955 WIP: RHEL 8/CentOS 8 docs
  docs/source/install/ewc.rst
  docs/source/install/index.rst
  docs/source/install/rhel8.rst
  docs/source/install/system_requirements.rst
  docs/source/install/uninstall.rst
Labels: feature

#971 fix formatting type for EL8 docs
  docs/source/install/rhel8.rst
Labels: bug
