Repository StackStorm/st2docs, pull requests merged in 2020-05, with the labels that each got.

#982 Small doc typo - verb as syntax
  docs/source/reference/packs.rst
Labels: bug

#981 Add section how to make the metrics available to prometheus
  docs/source/reference/metrics.rst
Labels: feature

#984 Updating Development document from source with web ui installation steps
  docs/source/development/sources.rst
Labels: enhancement

#983 Update docker set-up -- seemed like missing steps
  docs/source/install/docker.rst
Labels: enhancement
