Repository StackStorm/st2docs, pull requests merged in 2021-08, with the labels that each got.

#1081 Add a warning about duplicate keys in rule criteria
  docs/source/rules.rst
Labels: enhancement

#1082 README fixups
  README.md
Labels: bug, enhancement, typo

#1084 Add global permissions to documentation
  docs/source/_includes/available_permission_types.rst
  scripts/generate-available-permission-types-table.py
Labels: enhancement, RFR
