Repository StackStorm/st2docs, pull requests merged in 2022-05, with the labels that each got.

#1119 Add list of magor 3.7 improvements to changelog.
  docs/source/roadmap.rst
Labels: maintenance

#1121 Fix upgrade notes for v3.7
  docs/source/install/upgrades.rst
  docs/source/upgrade_notes.rst
Labels: bug

#1120 Fix upgrade notes for v3.7
  docs/source/install/upgrades.rst
  docs/source/upgrade_notes.rst
Labels: bug

#1125 Slight reword erlang 25 warning
  docs/source/install/rhel8.rst
Labels: RFR, OS support

#1124 Erlang 25 issues 3 7
  docs/source/install/rhel8.rst
Labels: RFR, OS support
