Repository StackStorm/st2docs, pull requests merged in 2022-03, with the labels that each got.

#1113 Update documentation for Python 3.8 upgrade on EL8
  docs/source/development/sources.rst
  docs/source/install/upgrades.rst
  docs/source/upgrade_notes.rst
Labels: RFR, OS support

#1053 Add docs for new st2 action-alias test command
  docs/source/chatops/aliases.rst
Labels: docs-for-open-pr

#1115 Add documentation for additional housekeep options
  docs/source/troubleshooting/purging_old_data.rst
  docs/source/upgrade_notes.rst
Labels: enhancement, RFR
